/**
 * FUSE Cinema — VISUAL PROOF preview types (CV1).
 *
 * Every Cinema preset is meant to be represented by a standardized VISUAL
 * preview rendered from a locked canonical test scene. CSS gradients survive
 * ONLY as a temporary fallback while preview media is missing.
 *
 * Cinema-only: nothing here is imported outside `src/lib/cinema` /
 * `src/components/cinema`. No media is generated by this module.
 */

export type PreviewKind = "still" | "loop" | "still-swatches" | "strip";

/**
 * The locked canonical test scenes. The ONLY intentional difference between two
 * previews of the same category is the tested variable — subject, wardrobe,
 * background and camera stay constant inside a scene.
 */
export type CanonicalScene = "PORTRAIT" | "PRODUCT" | "ENVIRONMENT" | "JEWELRY";

/** Human-readable lock description per canonical scene (documentation only). */
export const CANONICAL_SCENE_LOCKS: Record<CanonicalScene, string> = {
  PORTRAIT:
    "Same model, same wardrobe, same seamless backdrop, same camera position and framing.",
  PRODUCT:
    "Same product on the same sweep, same table height, same camera position and framing.",
  ENVIRONMENT:
    "Same location plate, same time-of-day base, same camera position and framing.",
  JEWELRY:
    "Same physical piece on the same stand, same macro camera position and framing.",
};

/** One encoding of a preview asset (avif/webp still, webm/mp4 loop, …). */
export type PreviewSource = { src: string; type?: string };

export type PreviewMedia = {
  kind: PreviewKind;
  canonicalScene: CanonicalScene;
  /** The preset this media belongs to (enables registry lookups downstream). */
  presetId?: string;
  /** Image or video URL. When absent, the gradient fallback is used. */
  src?: string;
  /** Preferred encodings in priority order (avif → webp, webm → mp4). */
  sources?: PreviewSource[];
  /** Small derivative used for grid tiles when available. */
  thumbSrc?: string;
  /** Poster frame for `loop` previews. */
  poster?: string;
  /** Hex swatches for `still-swatches` previews. */
  swatches?: string[];
  /** Temporary CSS gradient — fallback ONLY. */
  fallbackGradient?: string;
};

/** Fields the CV10 registry may override for a preset. */
export type PreviewMediaOverride = Partial<
  Pick<PreviewMedia, "src" | "sources" | "thumbSrc" | "poster" | "swatches">
>;

/** Injected by `previewRegistry` so hosted media reaches every existing call site. */
type PreviewMediaLookup = (presetId: string) => (PreviewMediaOverride & { kind?: PreviewKind }) | undefined;

let previewMediaLookup: PreviewMediaLookup | null = null;

export function setPreviewMediaLookup(lookup: PreviewMediaLookup | null) {
  previewMediaLookup = lookup;
}


/** Per-control-category preview taxonomy. */
export type CinemaPreviewCategory =
  | "CAMERA"
  | "LENS"
  | "FOCAL_LENGTH"
  | "APERTURE"
  | "LIGHTING"
  | "COLOR"
  | "COMPOSITION"
  | "FOCUS"
  | "ATMOSPHERE"
  | "OPTICS"
  | "MOVEMENT"
  | "CHARACTER"
  | "FULL";

/**
 * Allowed preview kinds per category (first entry = primary/default kind).
 * FOCAL_LENGTH additionally requires ONE comparison strip (18/24/35/50/85/135).
 */
export const PREVIEW_KINDS_BY_CATEGORY: Record<CinemaPreviewCategory, PreviewKind[]> = {
  CAMERA: ["still"],
  LENS: ["still"],
  FOCAL_LENGTH: ["still", "strip"],
  APERTURE: ["still"],
  LIGHTING: ["still"],
  COLOR: ["still-swatches"],
  COMPOSITION: ["still"],
  FOCUS: ["still", "loop"],
  ATMOSPHERE: ["still"],
  OPTICS: ["still"],
  MOVEMENT: ["loop"],
  CHARACTER: ["still"],
  FULL: ["still"],
};

/** The comparison strip focal lengths (single strip asset for FOCAL_LENGTH). */
export const FOCAL_LENGTH_STRIP_MM = [18, 24, 35, 50, 85, 135] as const;

export const DEFAULT_CANONICAL_SCENE: Record<CinemaPreviewCategory, CanonicalScene> = {
  CAMERA: "PORTRAIT",
  LENS: "PORTRAIT",
  FOCAL_LENGTH: "PORTRAIT",
  APERTURE: "PORTRAIT",
  LIGHTING: "PORTRAIT",
  COLOR: "PORTRAIT",
  COMPOSITION: "PORTRAIT",
  FOCUS: "PORTRAIT",
  ATMOSPHERE: "ENVIRONMENT",
  OPTICS: "ENVIRONMENT",
  MOVEMENT: "PORTRAIT",
  CHARACTER: "PORTRAIT",
  FULL: "PORTRAIT",
};

/** Primary preview kind for a category. */
export function primaryPreviewKind(category: CinemaPreviewCategory): PreviewKind {
  return PREVIEW_KINDS_BY_CATEGORY[category][0];
}

/** Jewelry-tagged presets are proven on the JEWELRY canonical scene. */
export function isJewelryScoped(input: { category?: string; tags?: string[] }): boolean {
  const haystack = [input.category ?? "", ...(input.tags ?? [])].join(" ").toLowerCase();
  return haystack.includes("jewelry") || haystack.includes("diamond");
}

/** Default canonical scene for a preset, honouring jewelry scoping. */
export function defaultCanonicalScene(
  category: CinemaPreviewCategory,
  preset?: { category?: string; tags?: string[] },
): CanonicalScene {
  if (preset && isJewelryScoped(preset)) return "JEWELRY";
  return DEFAULT_CANONICAL_SCENE[category];
}

/** How well a control has been proven across models. */
export type CinemaControlValidation = {
  presetId: string;
  modelsTested: string[];
  /** 0–100: how visibly the control changes the canonical scene. */
  visibleDifferenceScore: number;
  /** 0–100: how repeatable the change is across runs/models. */
  consistencyScore: number;
  supportType: "NATIVE" | "PROMPT_PROVEN" | "PROMPT_EXPERIMENTAL" | "UNSUPPORTED";
};

/** Additive mixin every builtin preset shape carries (all optional). */
export type PreviewablePreset = {
  preview?: PreviewMedia;
  validation?: CinemaControlValidation;
};

/**
 * Normalize a preset into renderable PreviewMedia. Falls back to the legacy CSS
 * gradient / swatch data when no media asset exists yet.
 */
export function resolvePreviewMedia(args: {
  category: CinemaPreviewCategory;
  preset: {
    id?: string;
    category?: string;
    tags?: string[];
    thumbnail?: string;
    preview?: PreviewMedia;
  };
  /** Swatch hexes for COLOR presets when `preview.swatches` is absent. */
  swatches?: string[];
}): PreviewMedia {
  const { category, preset } = args;
  const registered = preset.id ? previewMediaLookup?.(preset.id) : undefined;
  const kind = registered?.kind ?? preset.preview?.kind ?? primaryPreviewKind(category);
  const swatches = registered?.swatches ?? preset.preview?.swatches ?? args.swatches;
  return {
    kind,
    canonicalScene: preset.preview?.canonicalScene ?? defaultCanonicalScene(category, preset),
    presetId: preset.id,
    src: registered?.src ?? preset.preview?.src,
    sources: registered?.sources?.length ? registered.sources : preset.preview?.sources,
    thumbSrc: registered?.thumbSrc ?? preset.preview?.thumbSrc,
    poster: registered?.poster ?? preset.preview?.poster,
    swatches,
    fallbackGradient: preset.preview?.fallbackGradient ?? preset.thumbnail,
  };
}


/** True when the preview still needs a real media asset produced. */
export function needsMedia(media: PreviewMedia): boolean {
  if (media.kind === "still-swatches") return false;
  return !media.src;
}
