/**
 * FUSE Cinema — composition + focus preset code data (no DB).
 * Isolated to Cinema; nothing here is imported by other product surfaces.
 */

import type { CompositionSetup, FocusSetup } from "@/lib/cinema/types";

export type CompositionPreset = {
  id: string;
  name: string;
  hint: string;
  value: CompositionSetup;
};

export const COMPOSITION_PRESETS: CompositionPreset[] = [
  {
    id: "center-hero",
    name: "Center Hero",
    hint: "Subject dead center, balanced weight",
    value: {
      framing: "medium",
      rule: "center",
      subjectPlacement: "center",
      horizon: "center",
      subjectX: 50,
      subjectY: 50,
      horizonPosition: 50,
      headroomAmount: 50,
      leadRoomAmount: 50,
      negativeSpace: 40,
      framingScale: 50,
      cameraHeight: 50,
      tiltDegrees: 0,
    },
  },
  {
    id: "symmetrical",
    name: "Symmetrical",
    hint: "Mirrored frame, architectural balance",
    value: {
      framing: "medium wide",
      rule: "symmetry",
      subjectPlacement: "center",
      horizon: "center",
      subjectX: 50,
      subjectY: 50,
      horizonPosition: 50,
      headroomAmount: 50,
      leadRoomAmount: 50,
      negativeSpace: 45,
      framingScale: 45,
      cameraHeight: 50,
      tiltDegrees: 0,
    },
  },
  {
    id: "rule-of-thirds",
    name: "Rule of Thirds",
    hint: "Subject on a third line",
    value: {
      framing: "medium",
      rule: "rule-of-thirds",
      subjectPlacement: "left third",
      horizon: "lower third",
      subjectX: 33,
      subjectY: 45,
      horizonPosition: 66,
      headroomAmount: 45,
      leadRoomAmount: 60,
      negativeSpace: 55,
      framingScale: 50,
      cameraHeight: 50,
      tiltDegrees: 0,
    },
  },
  {
    id: "negative-space-left",
    name: "Negative Space Left",
    hint: "Subject right, open air left",
    value: {
      framing: "medium",
      rule: "negative-space",
      subjectPlacement: "right",
      horizon: "lower third",
      subjectX: 72,
      subjectY: 50,
      horizonPosition: 65,
      headroomAmount: 50,
      leadRoomAmount: 70,
      negativeSpace: 75,
      framingScale: 45,
      cameraHeight: 50,
      tiltDegrees: 0,
    },
  },
  {
    id: "negative-space-right",
    name: "Negative Space Right",
    hint: "Subject left, open air right",
    value: {
      framing: "medium",
      rule: "negative-space",
      subjectPlacement: "left",
      horizon: "lower third",
      subjectX: 28,
      subjectY: 50,
      horizonPosition: 65,
      headroomAmount: 50,
      leadRoomAmount: 70,
      negativeSpace: 75,
      framingScale: 45,
      cameraHeight: 50,
      tiltDegrees: 0,
    },
  },
  {
    id: "top-heavy",
    name: "Top Heavy",
    hint: "Visual mass in the upper frame",
    value: {
      framing: "medium",
      rule: "weighted",
      subjectPlacement: "upper center",
      horizon: "lower quarter",
      subjectX: 50,
      subjectY: 32,
      horizonPosition: 78,
      headroomAmount: 25,
      leadRoomAmount: 50,
      negativeSpace: 55,
      framingScale: 50,
      cameraHeight: 45,
      tiltDegrees: 0,
    },
  },
  {
    id: "bottom-heavy",
    name: "Bottom Heavy",
    hint: "Visual mass in the lower frame",
    value: {
      framing: "medium",
      rule: "weighted",
      subjectPlacement: "lower center",
      horizon: "upper quarter",
      subjectX: 50,
      subjectY: 70,
      horizonPosition: 25,
      headroomAmount: 75,
      leadRoomAmount: 50,
      negativeSpace: 55,
      framingScale: 50,
      cameraHeight: 55,
      tiltDegrees: 0,
    },
  },
  {
    id: "high-angle",
    name: "High Angle",
    hint: "Camera above the subject looking down",
    value: {
      framing: "medium",
      rule: "center",
      subjectPlacement: "center",
      horizon: "high",
      subjectX: 50,
      subjectY: 55,
      horizonPosition: 82,
      headroomAmount: 40,
      leadRoomAmount: 50,
      negativeSpace: 45,
      framingScale: 50,
      cameraHeight: 82,
      tiltDegrees: 0,
    },
  },
  {
    id: "low-angle",
    name: "Low Angle",
    hint: "Camera below the subject, heroic",
    value: {
      framing: "medium",
      rule: "center",
      subjectPlacement: "center",
      horizon: "low",
      subjectX: 50,
      subjectY: 45,
      horizonPosition: 18,
      headroomAmount: 55,
      leadRoomAmount: 50,
      negativeSpace: 45,
      framingScale: 50,
      cameraHeight: 18,
      tiltDegrees: 0,
    },
  },
  {
    id: "dutch",
    name: "Dutch",
    hint: "Rolled horizon, tension",
    value: {
      framing: "medium close",
      rule: "dynamic",
      subjectPlacement: "center",
      horizon: "tilted",
      subjectX: 50,
      subjectY: 50,
      horizonPosition: 55,
      headroomAmount: 45,
      leadRoomAmount: 50,
      negativeSpace: 45,
      framingScale: 55,
      cameraHeight: 50,
      tiltDegrees: 12,
    },
  },
  {
    id: "top-down",
    name: "Top Down",
    hint: "Straight overhead, plan view",
    value: {
      framing: "medium",
      rule: "grid",
      subjectPlacement: "center",
      horizon: "none",
      subjectX: 50,
      subjectY: 50,
      horizonPosition: 100,
      headroomAmount: 50,
      leadRoomAmount: 50,
      negativeSpace: 50,
      framingScale: 55,
      cameraHeight: 100,
      tiltDegrees: 0,
    },
  },
  {
    id: "flat-lay",
    name: "Flat Lay",
    hint: "Overhead product layout, even margins",
    value: {
      framing: "tabletop",
      rule: "grid",
      subjectPlacement: "center",
      horizon: "none",
      subjectX: 50,
      subjectY: 50,
      horizonPosition: 100,
      headroomAmount: 50,
      leadRoomAmount: 50,
      negativeSpace: 60,
      framingScale: 45,
      cameraHeight: 100,
      tiltDegrees: 0,
    },
  },
  {
    id: "wide-environmental",
    name: "Wide Environmental",
    hint: "Subject small inside the location",
    value: {
      framing: "wide",
      rule: "rule-of-thirds",
      subjectPlacement: "left third",
      horizon: "lower third",
      subjectX: 35,
      subjectY: 60,
      horizonPosition: 66,
      headroomAmount: 70,
      leadRoomAmount: 60,
      negativeSpace: 80,
      framingScale: 15,
      cameraHeight: 50,
      tiltDegrees: 0,
    },
  },
  {
    id: "tight-portrait",
    name: "Tight Portrait",
    hint: "Shoulders-up, intimate",
    value: {
      framing: "close-up",
      rule: "center",
      subjectPlacement: "center",
      horizon: "none",
      subjectX: 50,
      subjectY: 45,
      horizonPosition: 50,
      headroomAmount: 30,
      leadRoomAmount: 50,
      negativeSpace: 20,
      framingScale: 80,
      cameraHeight: 50,
      tiltDegrees: 0,
    },
  },
  {
    id: "extreme-close-up",
    name: "Extreme Close Up",
    hint: "Detail fills the frame",
    value: {
      framing: "extreme close-up",
      rule: "center",
      subjectPlacement: "center",
      horizon: "none",
      subjectX: 50,
      subjectY: 50,
      horizonPosition: 50,
      headroomAmount: 15,
      leadRoomAmount: 50,
      negativeSpace: 10,
      framingScale: 92,
      cameraHeight: 50,
      tiltDegrees: 0,
    },
  },
  {
    id: "macro-crop",
    name: "Macro Crop",
    hint: "Micro-detail, surface texture",
    value: {
      framing: "macro",
      rule: "center",
      subjectPlacement: "center",
      horizon: "none",
      subjectX: 50,
      subjectY: 50,
      horizonPosition: 50,
      headroomAmount: 10,
      leadRoomAmount: 50,
      negativeSpace: 8,
      framingScale: 98,
      cameraHeight: 50,
      tiltDegrees: 0,
    },
  },
  {
    id: "product-floating",
    name: "Product Floating",
    hint: "Object suspended, clean margins",
    value: {
      framing: "medium close",
      rule: "center",
      subjectPlacement: "center",
      horizon: "none",
      subjectX: 50,
      subjectY: 48,
      horizonPosition: 50,
      headroomAmount: 55,
      leadRoomAmount: 50,
      negativeSpace: 70,
      framingScale: 40,
      cameraHeight: 50,
      tiltDegrees: 0,
    },
  },
  {
    id: "editorial-off-center",
    name: "Editorial Off Center",
    hint: "Fashion-magazine asymmetry",
    value: {
      framing: "medium",
      rule: "asymmetry",
      subjectPlacement: "right of center",
      horizon: "lower third",
      subjectX: 62,
      subjectY: 55,
      horizonPosition: 68,
      headroomAmount: 65,
      leadRoomAmount: 35,
      negativeSpace: 62,
      framingScale: 42,
      cameraHeight: 48,
      tiltDegrees: 3,
    },
  },
];

export type FocusPreset = {
  id: string;
  name: string;
  hint: string;
  value: FocusSetup;
};

export const FOCUS_PRESETS: FocusPreset[] = [
  {
    id: "auto",
    name: "Auto",
    hint: "Let the model decide",
    value: {
      focusTarget: "auto",
      focusMode: "locked",
      presetId: "auto",
      presetName: "Auto",
      rackDirection: "none",
      depthOfFieldTightness: 50,
      breathing: 0,
      focusStack: false,
    },
  },
  {
    id: "subject-lock",
    name: "Subject Lock",
    hint: "Focus pinned to the subject",
    value: {
      focusTarget: "subject",
      focusMode: "follow",
      focusPlaneDepth: "subject plane",
      presetId: "subject-lock",
      presetName: "Subject Lock",
      rackDirection: "none",
      depthOfFieldTightness: 55,
      breathing: 0,
      focusStack: false,
    },
  },
  {
    id: "deep-focus",
    name: "Deep Focus",
    hint: "Everything sharp front to back",
    value: {
      focusTarget: "whole scene",
      focusMode: "locked",
      focusPlaneDepth: "hyperfocal",
      presetId: "deep-focus",
      presetName: "Deep Focus",
      rackDirection: "none",
      depthOfFieldTightness: 10,
      breathing: 0,
      focusStack: false,
    },
  },
  {
    id: "shallow",
    name: "Shallow",
    hint: "Subject sharp, background soft",
    value: {
      focusTarget: "subject",
      focusMode: "locked",
      focusPlaneDepth: "subject plane",
      presetId: "shallow",
      presetName: "Shallow",
      rackDirection: "none",
      depthOfFieldTightness: 75,
      breathing: 0,
      focusStack: false,
    },
  },
  {
    id: "ultra-shallow",
    name: "Ultra Shallow",
    hint: "Razor plane, heavy fall-off",
    value: {
      focusTarget: "subject detail",
      focusMode: "locked",
      focusPlaneDepth: "razor plane",
      presetId: "ultra-shallow",
      presetName: "Ultra Shallow",
      rackDirection: "none",
      depthOfFieldTightness: 95,
      breathing: 0,
      focusStack: false,
    },
  },
  {
    id: "rack-near-far",
    name: "Rack Near→Far",
    hint: "Pull focus from foreground to background",
    value: {
      focusTarget: "foreground then background",
      focusMode: "rack",
      focusPlaneDepth: "near to far",
      presetId: "rack-near-far",
      presetName: "Rack Near→Far",
      rackDirection: "near-to-far",
      depthOfFieldTightness: 78,
      breathing: 10,
      focusStack: false,
    },
  },
  {
    id: "rack-far-near",
    name: "Rack Far→Near",
    hint: "Pull focus from background to foreground",
    value: {
      focusTarget: "background then foreground",
      focusMode: "rack",
      focusPlaneDepth: "far to near",
      presetId: "rack-far-near",
      presetName: "Rack Far→Near",
      rackDirection: "far-to-near",
      depthOfFieldTightness: 78,
      breathing: 10,
      focusStack: false,
    },
  },
  {
    id: "focus-chase",
    name: "Focus Chase",
    hint: "Focus hunts the moving subject",
    value: {
      focusTarget: "moving subject",
      focusMode: "follow",
      focusPlaneDepth: "tracking plane",
      presetId: "focus-chase",
      presetName: "Focus Chase",
      rackDirection: "none",
      depthOfFieldTightness: 70,
      breathing: 18,
      focusStack: false,
    },
  },
  {
    id: "macro-plane",
    name: "Macro Plane",
    hint: "Tiny plane on a micro detail",
    value: {
      focusTarget: "micro detail",
      focusMode: "locked",
      focusPlaneDepth: "macro plane",
      presetId: "macro-plane",
      presetName: "Macro Plane",
      rackDirection: "none",
      depthOfFieldTightness: 98,
      breathing: 0,
      focusStack: false,
    },
  },
  {
    id: "focus-stack",
    name: "Focus Stack",
    hint: "Composite sharpness across planes",
    value: {
      focusTarget: "full product",
      focusMode: "locked",
      focusPlaneDepth: "stacked planes",
      presetId: "focus-stack",
      presetName: "Focus Stack",
      rackDirection: "none",
      depthOfFieldTightness: 20,
      breathing: 0,
      focusStack: true,
    },
  },
  {
    id: "vintage-breathing",
    name: "Vintage Breathing",
    hint: "Older glass, visible focus breathing",
    value: {
      focusTarget: "subject",
      focusMode: "follow",
      focusPlaneDepth: "subject plane",
      presetId: "vintage-breathing",
      presetName: "Vintage Breathing",
      rackDirection: "none",
      depthOfFieldTightness: 62,
      breathing: 70,
      focusStack: false,
    },
  },
];
