import { useState } from "react";
import { CRO_PROOF_PAIRS, type CroProofPair } from "@/content/croProofPairs";
import { cn } from "@/lib/utils";

/**
 * Real input → output proof pairs. No placeholder imagery: if a file is
 * missing, the slot renders an internal "MISSING REAL PAIR" card.
 *
 * `internalLabels` must stay false on any customer-facing surface — it controls
 * the "APPROVAL NEEDED" badge and the missing-pair diagnostics.
 */
export default function BeforeAfterProofPreview({
  pairs = CRO_PROOF_PAIRS,
  compact = false,
  internalLabels = false,
  className,
}: {
  pairs?: CroProofPair[];
  compact?: boolean;
  internalLabels?: boolean;
  className?: string;
}) {
  const [broken, setBroken] = useState<Record<string, true>>({});
  const markBroken = (id: string) => setBroken((prev) => ({ ...prev, [id]: true }));
  const visible = compact ? pairs.slice(0, 2) : pairs;

  return (
    <section className={cn("space-y-4", className)}>
      <h2 className="text-sm font-semibold uppercase tracking-[0.14em] text-muted-foreground">
        From product photo to full campaign
      </h2>
      <div
        className={cn(
          "grid gap-4",
          compact ? "sm:grid-cols-2" : "sm:grid-cols-2 xl:grid-cols-3",
        )}
      >
        {visible.map((pair) => {
          const isBroken = broken[pair.id];
          if (isBroken) {
            return (
              <div
                key={pair.id}
                className="rounded-[18px] border border-dashed border-border bg-card/60 p-5 text-sm text-muted-foreground"
              >
                <p className="font-semibold text-foreground">
                  {internalLabels ? `MISSING REAL PAIR — job ${pair.jobId}` : "Example unavailable"}
                </p>
                <p className="mt-2">
                  {pair.template} · {pair.useCase}
                </p>
              </div>
            );
          }
          return (
            <figure
              key={pair.id}
              className="overflow-hidden rounded-[18px] border border-border/70 bg-card"
            >
              <div className="grid grid-cols-2 gap-px bg-border/60">
                <div className="bg-card">
                  <p className="px-3 pt-3 text-[11px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">
                    Input — what was uploaded
                  </p>
                  <img
                    src={pair.inputSrc}
                    alt={`${pair.template} product photo that was uploaded`}
                    loading="lazy"
                    onError={() => markBroken(pair.id)}
                    className="aspect-[3/4] w-full object-contain p-3"
                  />
                </div>
                <div className="bg-card">
                  <p className="px-3 pt-3 text-[11px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">
                    Output — generated frame
                  </p>
                  {pair.outputType === "video" ? (
                    <video
                      src={pair.outputSrc}
                      muted
                      loop
                      autoPlay
                      playsInline
                      preload="metadata"
                      onError={() => markBroken(pair.id)}
                      className="aspect-[3/4] w-full object-cover"
                    />
                  ) : (
                    <img
                      src={pair.outputSrc}
                      alt={`${pair.template} campaign frame generated by FUSE`}
                      loading="lazy"
                      onError={() => markBroken(pair.id)}
                      className="aspect-[3/4] w-full object-cover"
                    />
                  )}
                </div>
              </div>
              <figcaption className="flex flex-wrap items-center justify-between gap-2 border-t border-border/70 px-3 py-2.5 text-sm">
                <span className="text-foreground">
                  {pair.template} · {pair.useCase}
                </span>
                {internalLabels ? (
                  <span className="rounded-full border border-border px-2 py-0.5 text-[10px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">
                    Approval needed
                  </span>
                ) : null}
              </figcaption>
            </figure>
          );
        })}
      </div>
    </section>
  );
}
