// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Hardcoding these to bypass the Lovable environment sync bug
const SUPABASE_URL = "https://ykrrwgkxgidoavtzcumk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_UPAfU3Vvfy6ffQIGxAM1rg_Q426Hmze";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true, // Added this for better redirect handling
  },
});
